### ISSUE TITLE
安装失败 CenOS

### ISSUE THREAD

**Issue by bihubihu** [BYVoid/OpenCC#295] opened 2018-05-21 09:57 UTC
[root@localhost usr]# cd OpenCC
[root@localhost OpenCC]# make
mkdir -p build/rel
(cd build/rel; cmake \
	-DBUILD_DOCUMENTATION:BOOL=ON \
	-DENABLE_GTEST:BOOL=OFF \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr \
	../..)
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/OpenCC/build/rel
make -C build/rel VERBOSE= PREFIX=/usr
make[1]: Entering directory `/usr/OpenCC/build/rel'
make[2]: Entering directory `/usr/OpenCC/build/rel'
make[3]: Entering directory `/usr/OpenCC/build/rel'
make[3]: Leaving directory `/usr/OpenCC/build/rel'
make[3]: Entering directory `/usr/OpenCC/build/rel'
[  2%] Building CXX object src/CMakeFiles/libopencc.dir/BinaryDict.cpp.o
In file included from /usr/OpenCC/src/Common.hpp:43,
                 from /usr/OpenCC/src/BinaryDict.hpp:21,
                 from /usr/OpenCC/src/BinaryDict.cpp:19:
/usr/OpenCC/src/Exception.hpp:43: error: expected ‘;’ before ‘noexcept’
/usr/OpenCC/src/Exception.hpp:45: error: expected ‘;’ before ‘protected’
In file included from /usr/OpenCC/src/Common.hpp:45,
                 from /usr/OpenCC/src/BinaryDict.hpp:21,
                 from /usr/OpenCC/src/BinaryDict.cpp:19:
/usr/OpenCC/src/Optional.hpp: In constructor ‘opencc::Optional<T*>::Optional()’:
/usr/OpenCC/src/Optional.hpp:62: error: ‘nullptr’ was not declared in this scope
/usr/OpenCC/src/Optional.hpp: In member function ‘bool opencc::Optional<T*>::IsNull() const’:
/usr/OpenCC/src/Optional.hpp:70: error: ‘nullptr’ was not declared in this scope
In file included from /usr/OpenCC/src/DictEntry.hpp:22,
                 from /usr/OpenCC/src/Dict.hpp:22,
                 from /usr/OpenCC/src/SerializableDict.hpp:21,
                 from /usr/OpenCC/src/BinaryDict.hpp:22,
                 from /usr/OpenCC/src/BinaryDict.cpp:19:
/usr/OpenCC/src/UTF8Util.hpp: In static member function ‘static std::string opencc::UTF8Util::Join(const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, const std::string&)’:
/usr/OpenCC/src/UTF8Util.hpp:218: error: expected initializer before ‘:’ token
/usr/OpenCC/src/UTF8Util.hpp:226: error: expected primary-expression at end of input
/usr/OpenCC/src/UTF8Util.hpp:226: error: expected ‘;’ at end of input
/usr/OpenCC/src/UTF8Util.hpp:226: error: expected primary-expression at end of input
/usr/OpenCC/src/UTF8Util.hpp:226: error: expected ‘)’ at end of input
/usr/OpenCC/src/UTF8Util.hpp:226: error: expected statement at end of input
/usr/OpenCC/src/UTF8Util.hpp:217: warning: unused variable ‘first’
/usr/OpenCC/src/UTF8Util.hpp:226: error: expected ‘}’ at end of input
/usr/OpenCC/src/UTF8Util.hpp:226: warning: no return statement in function returning non-void
/usr/OpenCC/src/UTF8Util.hpp: In static member function ‘static std::string opencc::UTF8Util::Join(const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)’:
/usr/OpenCC/src/UTF8Util.hpp:233: error: expected initializer before ‘:’ token
/usr/OpenCC/src/UTF8Util.hpp:236: error: expected primary-expression before ‘return’
/usr/OpenCC/src/UTF8Util.hpp:236: error: expected ‘;’ before ‘return’
/usr/OpenCC/src/UTF8Util.hpp:236: error: expected primary-expression before ‘return’
/usr/OpenCC/src/UTF8Util.hpp:236: error: expected ‘)’ before ‘return’
In file included from /usr/OpenCC/src/DictEntry.hpp:23,
                 from /usr/OpenCC/src/Dict.hpp:22,
                 from /usr/OpenCC/src/SerializableDict.hpp:21,
                 from /usr/OpenCC/src/BinaryDict.hpp:22,
                 from /usr/OpenCC/src/BinaryDict.cpp:19:
/usr/OpenCC/src/Segments.hpp: In constructor ‘opencc::Segments::Segments(std::initializer_list<const char*>)’:
/usr/OpenCC/src/Segments.hpp:33: error: expected initializer before ‘:’ token
/usr/OpenCC/src/Segments.hpp:36: error: expected primary-expression before ‘}’ token
/usr/OpenCC/src/Segments.hpp:36: error: expected ‘;’ before ‘}’ token
/usr/OpenCC/src/Segments.hpp:36: error: expected primary-expression before ‘}’ token
/usr/OpenCC/src/Segments.hpp:36: error: expected ‘)’ before ‘}’ token
/usr/OpenCC/src/Segments.hpp:36: error: expected primary-expression before ‘}’ token
/usr/OpenCC/src/Segments.hpp:36: error: expected ‘;’ before ‘}’ token
/usr/OpenCC/src/Segments.hpp: In constructor ‘opencc::Segments::Segments(std::initializer_list<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >)’:
/usr/OpenCC/src/Segments.hpp:39: error: expected initializer before ‘:’ token
/usr/OpenCC/src/Segments.hpp:42: error: expected primary-expression before ‘}’ token
/usr/OpenCC/src/Segments.hpp:42: error: expected ‘;’ before ‘}’ token
/usr/OpenCC/src/Segments.hpp:42: error: expected primary-expression before ‘}’ token
/usr/OpenCC/src/Segments.hpp:42: error: expected ‘)’ before ‘}’ token
/usr/OpenCC/src/Segments.hpp:42: error: expected primary-expression before ‘}’ token
/usr/OpenCC/src/Segments.hpp:42: error: expected ‘;’ before ‘}’ token
/usr/OpenCC/src/Segments.hpp: In member function ‘std::string opencc::Segments::ToString() const’:
/usr/OpenCC/src/Segments.hpp:98: error: expected initializer before ‘:’ token
/usr/OpenCC/src/Segments.hpp:101: error: expected primary-expression before ‘return’
/usr/OpenCC/src/Segments.hpp:101: error: expected ‘;’ before ‘return’
/usr/OpenCC/src/Segments.hpp:101: error: expected primary-expression before ‘return’
/usr/OpenCC/src/Segments.hpp:101: error: expected ‘)’ before ‘return’
In file included from /usr/OpenCC/src/Dict.hpp:22,
                 from /usr/OpenCC/src/SerializableDict.hpp:21,
                 from /usr/OpenCC/src/BinaryDict.hpp:22,
                 from /usr/OpenCC/src/BinaryDict.cpp:19:
/usr/OpenCC/src/DictEntry.hpp: In constructor ‘opencc::StrMultiValueDictEntry::StrMultiValueDictEntry(const std::string&, const std::vector<const char*, std::allocator<const char*> >&)’:
/usr/OpenCC/src/DictEntry.hpp:131: error: expected initializer before ‘:’ token
/usr/OpenCC/src/DictEntry.hpp:134: error: expected primary-expression before ‘}’ token
/usr/OpenCC/src/DictEntry.hpp:134: error: expected ‘;’ before ‘}’ token
/usr/OpenCC/src/DictEntry.hpp:134: error: expected primary-expression before ‘}’ token
/usr/OpenCC/src/DictEntry.hpp:134: error: expected ‘)’ before ‘}’ token
/usr/OpenCC/src/DictEntry.hpp:134: error: expected primary-expression before ‘}’ token
/usr/OpenCC/src/DictEntry.hpp:134: error: expected ‘;’ before ‘}’ token
/usr/OpenCC/src/DictEntry.hpp: In member function ‘virtual std::vector<const char*, std::allocator<const char*> > opencc::StrMultiValueDictEntry::Values() const’:
/usr/OpenCC/src/DictEntry.hpp:144: error: expected initializer before ‘:’ token
/usr/OpenCC/src/DictEntry.hpp:147: error: expected primary-expression before ‘return’
/usr/OpenCC/src/DictEntry.hpp:147: error: expected ‘;’ before ‘return’
/usr/OpenCC/src/DictEntry.hpp:147: error: expected primary-expression before ‘return’
/usr/OpenCC/src/DictEntry.hpp:147: error: expected ‘)’ before ‘return’
In file included from /usr/OpenCC/src/BinaryDict.cpp:20:
/usr/OpenCC/src/Lexicon.hpp: In destructor ‘opencc::Lexicon::~Lexicon()’:
/usr/OpenCC/src/Lexicon.hpp:34: error: expected initializer before ‘:’ token
/usr/OpenCC/src/Lexicon.hpp:37: error: expected primary-expression before ‘}’ token
/usr/OpenCC/src/Lexicon.hpp:37: error: expected ‘;’ before ‘}’ token
/usr/OpenCC/src/Lexicon.hpp:37: error: expected primary-expression before ‘}’ token
/usr/OpenCC/src/Lexicon.hpp:37: error: expected ‘)’ before ‘}’ token
/usr/OpenCC/src/Lexicon.hpp:37: error: expected primary-expression before ‘}’ token
/usr/OpenCC/src/Lexicon.hpp:37: error: expected ‘;’ before ‘}’ token
/usr/OpenCC/src/BinaryDict.cpp: In member function ‘size_t opencc::BinaryDict::KeyMaxLength() const’:
/usr/OpenCC/src/BinaryDict.cpp:26: error: expected initializer before ‘:’ token
/usr/OpenCC/src/BinaryDict.cpp:29: error: expected primary-expression before ‘return’
/usr/OpenCC/src/BinaryDict.cpp:29: error: expected ‘;’ before ‘return’
/usr/OpenCC/src/BinaryDict.cpp:29: error: expected primary-expression before ‘return’
/usr/OpenCC/src/BinaryDict.cpp:29: error: expected ‘)’ before ‘return’
/usr/OpenCC/src/BinaryDict.cpp: In member function ‘virtual void opencc::BinaryDict::SerializeToFile(FILE*) const’:
/usr/OpenCC/src/BinaryDict.cpp:49: error: expected initializer before ‘:’ token
/usr/OpenCC/src/BinaryDict.cpp:179: error: expected primary-expression at end of input
/usr/OpenCC/src/BinaryDict.cpp:179: error: expected ‘;’ at end of input
/usr/OpenCC/src/BinaryDict.cpp:179: error: expected primary-expression at end of input
/usr/OpenCC/src/BinaryDict.cpp:179: error: expected ‘)’ at end of input
/usr/OpenCC/src/BinaryDict.cpp:179: error: expected statement at end of input
/usr/OpenCC/src/BinaryDict.cpp:48: warning: unused variable ‘keyCursor’
/usr/OpenCC/src/BinaryDict.cpp:48: warning: unused variable ‘valueCursor’
/usr/OpenCC/src/BinaryDict.cpp:179: error: expected ‘}’ at end of input
make[3]: *** [src/CMakeFiles/libopencc.dir/BinaryDict.cpp.o] Error 1
make[3]: Leaving directory `/usr/OpenCC/build/rel'
make[2]: *** [src/CMakeFiles/libopencc.dir/all] Error 2
make[2]: Leaving directory `/usr/OpenCC/build/rel'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/OpenCC/build/rel'
make: *** [build] Error 2

**Comment by ryandesign** [comment] 2018-06-13 19:39
I am also seeing this build failure on macOS Sierra 10.12.6 with Xcode 9.2 and clang version "Apple LLVM version 9.0.0 (clang-900.0.39.2)".

**Comment by ryandesign** [comment] 2018-10-13 09:43
It seems that the features being used here are new in C++11, but my compiler defaults to an earlier C++ standard, so the build fails. The problem is fixed by adding `-std=c++11` to `CXXFLAGS`.

**Closed** 2020-01-25 07:31 UTC

**Comment by ryandesign** [comment] 2020-04-20 03:38
Why is this issue closed? It has not been fixed. Please reopen it until the build system has been fixed to add the `-std=c++11` flag.

**Comment by sgalal** [comment] 2020-04-20 07:01
@ryandesign 

> Why is this issue closed? It has not been fixed. Please reopen it until the build system has been fixed to add the `-std=c++11` flag.

Because I could not reproduce this error on CentOS Linux release 7.7.1908 (Core), which is the same as the issue author’s environment.

if you still encounter problems, please attach a correctly formatted error message.

**Comment by ryandesign** [comment] 2020-04-25 06:12
Thanks, I see now that the cause of my issue was different. I've submitted https://github.com/BYVoid/OpenCC/pull/381 to fix it.
