### ISSUE TITLE
1.0.5 bintray?

### ISSUE THREAD

**Issue by ilovezfs** [BYVoid/OpenCC#239] opened 2017-04-02 07:50 UTC
Latest release on GitHub appears to be 1.0.5 but on Bintray the greatest version available is 1.0.4.

Should a new tarball be published on Bintray?

**Comment by ryandesign** [comment] 2017-04-12 04:49
Duplicate of #221.

**Comment by ilovezfs** [comment] 2017-04-12 05:38
@BYVoid ping on this.

**Closed** 2017-04-12 05:38 UTC
